[package]
name = "geoguessr_tracker"
version = "0.2.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"

[dev-dependencies]
rand = "0.8.5"

[profile.release]
opt-level = 3
strip = "symbols"
