[package]
name = "ben_24h"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
inquire = "0.7.5"
log = "0.4.22"

[dev-dependencies]
rand = "0.8.5"

[profile.release]
opt-level = 3
strip = "symbols"
